*** Starting uWSGI 2.0.21 (64bit) on [Tue Apr  4 19:22:27 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:30:06
os: Linux-5.10.134-13.al8.x86_64 #1 SMP Mon Jan 9 10:50:49 CST 2023
nodename: LaCorrect
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/hcjiang/backend
writing pidfile to uwsgi.pid
detected binary path: /data/hcjiang/miniconda3/envs/backend/bin/uwsgi
chdir() to /data/hcjiang/backend
your processes number limit is 61736
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "default" initialized: 1MB (key: 148 bytes, keys: 2960 bytes, data: 1310720 bytes, bitmap: 3 bytes) preallocated ***
uwsgi socket 0 bound to TCP address :5000 fd 4
Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0]
Python main interpreter initialized at 0x1136890
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 700088 bytes (683 KB) for 4 cores
*** Operational MODE: threaded ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8051)
spawned uWSGI worker 1 (pid: 8052, cores: 4)
cache sweeper thread enabled
Traceback (most recent call last):
  File "app.py", line 22, in <module>
    from model.preprocess.preprocess import preprocess
  File "/data/hcjiang/backend/./model/preprocess/preprocess.py", line 8, in <module>
    from model.preprocess.pdfparser.pdfparser import Converter
  File "/data/hcjiang/backend/./model/preprocess/pdfparser/pdfparser/__init__.py", line 1, in <module>
    from .converter import Converter
  File "/data/hcjiang/backend/./model/preprocess/pdfparser/pdfparser/converter.py", line 9, in <module>
    from .page.Page import Page
  File "/data/hcjiang/backend/./model/preprocess/pdfparser/pdfparser/page/Page.py", line 44, in <module>
    from ..common.Collection import BaseCollection
  File "/data/hcjiang/backend/./model/preprocess/pdfparser/pdfparser/common/Collection.py", line 9, in <module>
    from .algorithm import (solve_rects_intersection, graph_bfs)
  File "/data/hcjiang/backend/./model/preprocess/pdfparser/pdfparser/common/algorithm.py", line 3, in <module>
    import cv2 as cv
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.21 (64bit) on [Tue Apr  4 19:27:08 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:30:06
os: Linux-5.10.134-13.al8.x86_64 #1 SMP Mon Jan 9 10:50:49 CST 2023
nodename: LaCorrect
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/hcjiang/backend
writing pidfile to uwsgi.pid
detected binary path: /data/hcjiang/miniconda3/envs/backend/bin/uwsgi
chdir() to /data/hcjiang/backend
your processes number limit is 61736
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "default" initialized: 1MB (key: 148 bytes, keys: 2960 bytes, data: 1310720 bytes, bitmap: 3 bytes) preallocated ***
uwsgi socket 0 bound to TCP address :5000 fd 4
Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0]
Python main interpreter initialized at 0x277f890
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 700088 bytes (683 KB) for 4 cores
*** Operational MODE: threaded ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8157)
spawned uWSGI worker 1 (pid: 8158, cores: 4)
cache sweeper thread enabled
Traceback (most recent call last):
  File "app.py", line 25, in <module>
    from model.postprocess.postprocess import postprocess
  File "/data/hcjiang/backend/./model/postprocess/postprocess.py", line 2, in <module>
    from model.postprocess.ChERRANT.modules.annotator import Annotator
  File "/data/hcjiang/backend/./model/postprocess/ChERRANT/modules/annotator.py", line 2, in <module>
    from model.postprocess.ChERRANT.modules.alignment import read_cilin, read_confusion, Alignment
  File "/data/hcjiang/backend/./model/postprocess/ChERRANT/modules/alignment.py", line 3, in <module>
    from model.postprocess.ChERRANT.modules.tokenizer import Tokenizer
  File "/data/hcjiang/backend/./model/postprocess/ChERRANT/modules/tokenizer.py", line 3, in <module>
    from ltp import LTP
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/site-packages/ltp/__init__.py", line 8, in <module>
    from . import nn, utils
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/site-packages/ltp/utils/__init__.py", line 10, in <module>
    from .convertor import map2device, convert2npy
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/site-packages/ltp/utils/convertor.py", line 6, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs' from 'torch._six' (/data/hcjiang/miniconda3/envs/backend/lib/python3.8/site-packages/torch/_six.py)
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
SIGINT/SIGTERM received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.21 (64bit) on [Tue Apr  4 19:29:56 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:30:06
os: Linux-5.10.134-13.al8.x86_64 #1 SMP Mon Jan 9 10:50:49 CST 2023
nodename: LaCorrect
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/hcjiang/backend
writing pidfile to uwsgi.pid
detected binary path: /data/hcjiang/miniconda3/envs/backend/bin/uwsgi
chdir() to /data/hcjiang/backend
your processes number limit is 61736
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "default" initialized: 1MB (key: 148 bytes, keys: 2960 bytes, data: 1310720 bytes, bitmap: 3 bytes) preallocated ***
uwsgi socket 0 bound to TCP address :5000 fd 4
Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0]
Python main interpreter initialized at 0x19c9890
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 700088 bytes (683 KB) for 4 cores
*** Operational MODE: threaded ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8169)
spawned uWSGI worker 1 (pid: 8170, cores: 4)
cache sweeper thread enabled
USE CACHE UWSGI
[INFO] 日志系统启动
[INFO] 进程队列初始化
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x19c9890 pid: 8170 (default app)
[pid: 8170|app: 0|req: 1/1] 127.0.0.1 () {24 vars in 251 bytes} [Tue Apr  4 19:31:15 2023] GET / => generated 5 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 0)
[pid: 8170|app: 0|req: 2/2] 127.0.0.1 () {24 vars in 251 bytes} [Tue Apr  4 19:32:05 2023] GET / => generated 5 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 1)
SIGINT/SIGTERM received...killing workers...
Exception ignored in: <function Pool.__del__ at 0x7fd82f963af0>
Traceback (most recent call last):
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.21 (64bit) on [Tue Apr  4 19:45:48 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:30:06
os: Linux-5.10.134-13.al8.x86_64 #1 SMP Mon Jan 9 10:50:49 CST 2023
nodename: LaCorrect
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/hcjiang/backend
writing pidfile to uwsgi.pid
detected binary path: /data/hcjiang/miniconda3/envs/backend/bin/uwsgi
chdir() to /data/hcjiang/backend
your processes number limit is 61736
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "default" initialized: 1MB (key: 148 bytes, keys: 2960 bytes, data: 1310720 bytes, bitmap: 3 bytes) preallocated ***
uwsgi socket 0 bound to TCP address 0.0.0.0:5000 fd 4
Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0]
Python main interpreter initialized at 0x169ade0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 700088 bytes (683 KB) for 4 cores
*** Operational MODE: threaded ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8268)
spawned uWSGI worker 1 (pid: 8269, cores: 4)
cache sweeper thread enabled
USE CACHE UWSGI
[INFO] 日志系统启动
[INFO] 进程队列初始化
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x169ade0 pid: 8269 (default app)
[pid: 8269|app: 0|req: 1/1] 127.0.0.1 () {24 vars in 251 bytes} [Tue Apr  4 19:46:42 2023] GET / => generated 5 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 0)
[pid: 8269|app: 0|req: 2/2] 172.27.108.238 () {24 vars in 261 bytes} [Tue Apr  4 19:48:27 2023] GET / => generated 5 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 1)
[pid: 8269|app: 0|req: 3/3] 117.80.202.251 () {32 vars in 662 bytes} [Tue Apr  4 20:28:52 2023] GET / => generated 5 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 3)
[pid: 8269|app: 0|req: 4/4] 117.80.202.251 () {32 vars in 618 bytes} [Tue Apr  4 20:28:53 2023] GET /favicon.ico => generated 207 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 2)
uwsgi_proto_http_parser() -> client closed connection
[pid: 8269|app: 0|req: 5/5] 174.138.61.44 () {26 vars in 346 bytes} [Tue Apr  4 21:28:21 2023] GET / => generated 5 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 1)
uwsgi_proto_http_parser(): Connection reset by peer [proto/http.c line 463]
[pid: 8269|app: 0|req: 6/6] 205.210.31.19 () {22 vars in 486 bytes} [Tue Apr  4 22:17:07 2023] GET / => generated 5 bytes in 0 msecs (HTTP/1.0 200) 2 headers in 78 bytes (1 switches on core 2)
uwsgi_proto_http_parser() -> client closed connection
Traceback (most recent call last):
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/site-packages/flask/app.py", line 2523, in wsgi_app
    ctx = self.request_context(environ)
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/site-packages/flask/app.py", line 2440, in request_context
    return RequestContext(self, environ)
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/site-packages/flask/ctx.py", line 314, in __init__
    self.url_adapter = app.create_url_adapter(self.request)
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/site-packages/flask/app.py", line 2221, in create_url_adapter
    return self.url_map.bind_to_environ(
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/site-packages/werkzeug/routing/map.py", line 350, in bind_to_environ
    env["REQUEST_METHOD"],
KeyError: 'REQUEST_METHOD'
[pid: 8269|app: 0|req: 7/7] 104.152.52.9 () {8 vars in 85 bytes} [Wed Apr  5 00:46:48 2023]   => generated 0 bytes in 1 msecs ( 500) 0 headers in 0 bytes (0 switches on core 1)
[pid: 8269|app: 0|req: 8/8] 104.152.52.9 () {18 vars in 179 bytes} [Wed Apr  5 00:46:49 2023] GET / => generated 5 bytes in 0 msecs (HTTP/1.0 200) 2 headers in 78 bytes (1 switches on core 3)
[pid: 8269|app: 0|req: 9/9] 104.152.52.9 () {18 vars in 183 bytes} [Wed Apr  5 00:46:49 2023] OPTIONS / => generated 0 bytes in 0 msecs (RTSP/1.0 200) 3 headers in 105 bytes (0 switches on core 2)
[pid: 8269|app: 0|req: 10/10] 104.152.52.9 () {18 vars in 183 bytes} [Wed Apr  5 00:46:58 2023] OPTIONS / => generated 0 bytes in 0 msecs (HTTP/1.0 200) 3 headers in 105 bytes (0 switches on core 3)
uwsgi_proto_http_parser() -> client closed connection
uwsgi_proto_http_parser() -> client closed connection
uwsgi_proto_http_parser() -> client closed connection
uwsgi_proto_http_parser() -> client closed connection
uwsgi_proto_http_parser() -> client closed connection
uwsgi_proto_http_parser() -> client closed connection
Wed Apr  5 09:44:32 2023 - uwsgi_response_writev_headers_and_body_do(): Connection reset by peer [core/writer.c line 306] during GET / (117.80.202.251)
OSError: write error
[pid: 8269|app: 0|req: 11/11] 117.80.202.251 () {32 vars in 667 bytes} [Wed Apr  5 09:44:32 2023] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 0 bytes (0 switches on core 3)
[pid: 8269|app: 0|req: 12/12] 47.122.17.1 () {24 vars in 255 bytes} [Wed Apr  5 09:45:02 2023] GET / => generated 5 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 0)
...brutally killing workers...
Exception ignored in: <function Pool.__del__ at 0x7f65a7beac10>
Traceback (most recent call last):
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
!!! uWSGI process 8269 got Segmentation Fault !!!
worker 1 buried after 35 seconds
binary reloading uWSGI...
chdir() to /data/hcjiang/backend
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 4 mapped to socket 0 (0.0.0.0:5000)
running /data/hcjiang/miniconda3/envs/backend/bin/uwsgi
[uWSGI] getting INI configuration from app.ini
*** Starting uWSGI 2.0.21 (64bit) on [Wed Apr 12 12:46:02 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:30:06
os: Linux-5.10.134-13.al8.x86_64 #1 SMP Mon Jan 9 10:50:49 CST 2023
nodename: LaCorrect
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/hcjiang/backend
detected binary path: /data/hcjiang/miniconda3/envs/backend/bin/uwsgi
chdir() to /data/hcjiang/backend
your processes number limit is 61736
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "default" initialized: 1MB (key: 148 bytes, keys: 2960 bytes, data: 1310720 bytes, bitmap: 3 bytes) preallocated ***
uwsgi socket 0 inherited INET address :5000 fd 4
Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0]
Python main interpreter initialized at 0x1d78780
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 700088 bytes (683 KB) for 4 cores
*** Operational MODE: threaded ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 8268)
spawned uWSGI worker 1 (pid: 26922, cores: 4)
cache sweeper thread enabled
USE CACHE UWSGI
[INFO] 日志系统启动
[INFO] 进程队列初始化
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1d78780 pid: 26922 (default app)
*** Starting uWSGI 2.0.21 (64bit) on [Wed Apr 12 13:04:13 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:30:06
os: Linux-5.10.134-13.al8.x86_64 #1 SMP Mon Jan 9 10:50:49 CST 2023
nodename: LaCorrect
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/hcjiang/backend
writing pidfile to uwsgi.pid
detected binary path: /data/hcjiang/miniconda3/envs/backend/bin/uwsgi
chdir() to /data/hcjiang/backend
your processes number limit is 61736
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "default" initialized: 1MB (key: 148 bytes, keys: 2960 bytes, data: 1310720 bytes, bitmap: 3 bytes) preallocated ***
probably another instance of uWSGI is running on the same address (:5000).
bind(): Address already in use [core/socket.c line 769]
[pid: 26922|app: 0|req: 1/1] 127.0.0.1 () {24 vars in 251 bytes} [Wed Apr 12 13:32:02 2023] GET / => generated 5 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 0)
...brutally killing workers...
Exception ignored in: <function Pool.__del__ at 0x7f1d641fed30>
Traceback (most recent call last):
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/data/hcjiang/miniconda3/envs/backend/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
!!! uWSGI process 26922 got Segmentation Fault !!!
Thu Apr 13 16:13:22 2023 - worker 1 (pid: 26922) is taking too much time to die...NO MERCY !!!
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /data/hcjiang/backend
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 4 mapped to socket 0 (:5000)
running /data/hcjiang/miniconda3/envs/backend/bin/uwsgi
[uWSGI] getting INI configuration from app.ini
*** Starting uWSGI 2.0.21 (64bit) on [Thu Apr 13 16:13:23 2023] ***
compiled with version: 11.2.0 on 28 March 2023 07:30:06
os: Linux-5.10.134-13.al8.x86_64 #1 SMP Mon Jan 9 10:50:49 CST 2023
nodename: LaCorrect
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /data/hcjiang/backend
detected binary path: /data/hcjiang/miniconda3/envs/backend/bin/uwsgi
chdir() to /data/hcjiang/backend
your processes number limit is 61736
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "default" initialized: 1MB (key: 148 bytes, keys: 2960 bytes, data: 1310720 bytes, bitmap: 3 bytes) preallocated ***
uwsgi socket 0 inherited INET address :5000 fd 4
Python version: 3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC 11.2.0]
Python main interpreter initialized at 0x1196d10
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 700088 bytes (683 KB) for 4 cores
*** Operational MODE: threaded ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 8268)
spawned uWSGI worker 1 (pid: 30325, cores: 4)
cache sweeper thread enabled
USE CACHE UWSGI
[INFO] 日志系统启动
[INFO] 进程队列初始化
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1196d10 pid: 30325 (default app)
